# Generated by Django 4.1.7 on 2025-07-18 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('project_editors', models.ManyToManyField(blank=True, related_name='edited_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('project_members', models.ManyToManyField(blank=True, related_name='project_membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('workplace', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('id_image', models.ImageField(upload_to='user_applications/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_projects', models.ManyToManyField(blank=True, related_name='related_projects', to='inventory.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrashSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, null=True)),
                ('sample_type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
                ('well_id', models.CharField(max_length=100, null=True)),
                ('date_recorded', models.DateField(null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrashReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('pack_size', models.PositiveIntegerField(null=True)),
                ('pack_size_rem', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField()),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrashEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('equip_id', models.CharField(max_length=100, null=True)),
                ('serial_num', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('service_contract_start', models.DateField(null=True)),
                ('service_contract_end', models.DateField(null=True)),
                ('date_recorded', models.DateField()),
                ('donated_by', models.CharField(max_length=100, null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='TrashConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('pack_size', models.PositiveIntegerField(null=True)),
                ('pack_size_rem', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField()),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, null=True)),
                ('sample_type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
                ('well_id', models.CharField(max_length=100, null=True)),
                ('date_recorded', models.DateField(auto_now_add=True, null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.box')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
                ('shelf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shelf')),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('pack_size', models.PositiveIntegerField(null=True)),
                ('pack_size_rem', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('equip_id', models.CharField(max_length=100, null=True)),
                ('serial_num', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('service_contract_start', models.DateField(null=True)),
                ('service_contract_end', models.DateField(null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('donated_by', models.CharField(max_length=100, null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('product_code', models.CharField(max_length=100, null=True)),
                ('pack_size', models.PositiveIntegerField(null=True)),
                ('pack_size_rem', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project'),
        ),
        migrations.AddField(
            model_name='box',
            name='shelf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.shelf'),
        ),
    ]
