# Generated by Django 4.0.3 on 2023-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100)),
                ('threshold_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100)),
                ('threshold_value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('storage_location', models.CharField(max_length=100)),
                ('threshold_value', models.PositiveIntegerField()),
            ],
        ),
    ]
