# Generated by Django 4.0.3 on 2023-06-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='threshold_value',
        ),
        migrations.AddField(
            model_name='consumable',
            name='product_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_num',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='product_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='storage_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='threshold_value',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storage_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='storage_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reagent',
            name='threshold_value',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
