# Generated by Django 4.0.3 on 2023-06-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_equipment_threshold_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField()),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
