# Generated by Django 4.0.3 on 2023-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_trashconsumable'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashconsumable',
            name='storage_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
