# Generated by Django 4.0.3 on 2023-06-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_project_project_manager_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('workplace', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('id_image', models.ImageField(upload_to='user_applications/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
