# Generated by Django 4.0.3 on 2023-06-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_members', to='inventory.project'),
        ),
    ]
