# Generated by Django 4.0.3 on 2023-06-19 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_userprofile_managed_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
    ]
