# Generated by Django 4.0.3 on 2023-06-22 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0010_remove_userprofile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_editors',
            field=models.ManyToManyField(blank=True, related_name='edited_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_members',
            field=models.ManyToManyField(blank=True, related_name='project_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='managed_projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_projects', to='inventory.project'),
        ),
    ]
