# Generated by Django 4.0.3 on 2023-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='pack_size',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
