# Generated by Django 4.0.3 on 2023-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_consumable_pack_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='pack_size_rem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
