# Generated by Django 4.0.3 on 2023-07-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_consumable_pack_size_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashconsumable',
            name='pack_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trashconsumable',
            name='pack_size_rem',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
