# Generated by Django 4.0.3 on 2023-08-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_trashconsumable_pack_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='pack_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reagent',
            name='pack_size_rem',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='TrashReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=50)),
                ('pack_size', models.PositiveIntegerField(null=True)),
                ('pack_size_rem', models.PositiveIntegerField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('date_recorded', models.DateField()),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
    ]
