# Generated by Django 4.0.3 on 2023-08-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_reagent_pack_size_reagent_pack_size_rem_trashreagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='donated_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='equip_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_contract_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='service_contract_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
