# Generated by Django 4.0.3 on 2023-08-07 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_equipment_donated_by_equipment_equip_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('equip_id', models.CharField(max_length=100, null=True)),
                ('serial_num', models.CharField(max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('service_contract_start', models.DateField(null=True)),
                ('service_contract_end', models.DateField(null=True)),
                ('date_recorded', models.DateField()),
                ('donated_by', models.CharField(max_length=100, null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
    ]
