# Generated by Django 4.0.3 on 2023-08-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_trashequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('volume', models.PositiveIntegerField(null=True)),
                ('well_id', models.CharField(max_length=100, null=True)),
                ('storage_location', models.CharField(max_length=100, null=True)),
                ('threshold_value', models.PositiveIntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.project')),
            ],
        ),
    ]
