# Generated by Django 4.0.3 on 2023-08-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_rename_type_sample_sample_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trashsample',
            old_name='type',
            new_name='sample_type',
        ),
    ]
