# Generated by Django 4.0.3 on 2023-08-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_type_trashsample_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='trashsample',
            name='date_recorded',
            field=models.DateField(null=True),
        ),
    ]
